name: Python application

on:
  push:
    branches:
  pull_request:
    branches:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies
      run: |
        pipenv install --dev

    - name: Cache pipenv
      uses: actions/cache@v3
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-

    - name: Set up PostgreSQL
      uses: Harmon758/postgresql-action@v1
      with:
        postgresql version: '13'

    - name: Set up Django environment
      run: |
        cp example.env .env
        pipenv run python manage.py migrate
        pipenv run python manage.py collectstatic --noinput

    - name: Lint with flake8
      run: |
        # Activate the pipenv shell
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        # Activate the pipenv shell
        pipenv run pytest --maxfail=5 --disable-warnings
